// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKDgVYcA1d6G8woStqNLRj3qSuVstvt04',
    appId: '1:926656653960:web:220ecb600fd5bb901b4d3d',
    messagingSenderId: '926656653960',
    projectId: 'telemetry-system-8d017',
    authDomain: 'telemetry-system-8d017.firebaseapp.com',
    databaseURL: 'https://telemetry-system-8d017-default-rtdb.firebaseio.com',
    storageBucket: 'telemetry-system-8d017.appspot.com',
    measurementId: 'G-G9EYY5MZZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjCGWrtWhhOOVupMrCctcNJ86eS6CAIvo',
    appId: '1:926656653960:android:845e598a3569e0241b4d3d',
    messagingSenderId: '926656653960',
    projectId: 'telemetry-system-8d017',
    databaseURL: 'https://telemetry-system-8d017-default-rtdb.firebaseio.com',
    storageBucket: 'telemetry-system-8d017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZQ02ogQGEmulZM6u3z3V1XBBjLygIri8',
    appId: '1:926656653960:ios:502d5bdf9d8bee1f1b4d3d',
    messagingSenderId: '926656653960',
    projectId: 'telemetry-system-8d017',
    databaseURL: 'https://telemetry-system-8d017-default-rtdb.firebaseio.com',
    storageBucket: 'telemetry-system-8d017.appspot.com',
    iosClientId: '926656653960-cmc7lem0ah52da5bph66aghaj182l59h.apps.googleusercontent.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZQ02ogQGEmulZM6u3z3V1XBBjLygIri8',
    appId: '1:926656653960:ios:502d5bdf9d8bee1f1b4d3d',
    messagingSenderId: '926656653960',
    projectId: 'telemetry-system-8d017',
    databaseURL: 'https://telemetry-system-8d017-default-rtdb.firebaseio.com',
    storageBucket: 'telemetry-system-8d017.appspot.com',
    iosClientId: '926656653960-cmc7lem0ah52da5bph66aghaj182l59h.apps.googleusercontent.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );
}
